kind: pipeline
type: kubernetes
name: default

steps:
  # - name: print env variables
  #   image: busybox
  #   environment:
  #     FOO:
  #       from_secret: username
  #     TAG: ${CI_COMMIT_SHA:0:8}
  #   commands:
  #     - echo ${CI_COMMIT_SHA:0:8}
  #     - echo -n $FOO | base64
  #     - printenv

  # - name: build and publish image
  #   image: lbogdan/drone-docker:2
  #   settings:
  #     repo: lbogdan/k8s-simple-app
  #     tags:
  #       - ${CI_COMMIT_SHA:0:8}
  #     username:
  #       from_secret: docker_username
  #     password:
  #       from_secret: docker_password
  #   privileged: true

  - name: test kapp
    image: lbogdan/drone-kapp:1
    environment:
      KUBECONFIG: /kubeconfig
      KUBECONFIG_DATA:
        from_secret: kubeconfig_data
      ENV: staging
      IMAGE_TAG: 989b28ed
    commands:
      - echo $KUBECONFIG_DATA | base64 -d >/kubeconfig
      - cat k8s/simple-app.yaml | envsub | kapp deploy -a simple-app-$ENV -c -f - -y

trigger:
  event:
    - push
  branch:
    - main
