apiVersion: v1
kind: ConfigMap
metadata:
  name: simple-app-${ENV}
  namespace: luck
  labels:
    app: simple-app
    env: ${ENV}
data:
  ENV: ${ENV}
  PORT: "8080"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-app-${ENV}
  namespace: luck
  labels:
    app: simple-app
    env: ${ENV}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-app
      env: ${ENV}
  template:
    metadata:
      labels:
        app: simple-app
        env: ${ENV}
    spec:
      containers:
      - image: lbogdan/k8s-simple-app:${IMAGE_TAG}
        name: simple-app
        envFrom:
        - configMapRef:
            name: simple-app-${ENV}
---
apiVersion: v1
kind: Service
metadata:
  name: simple-app-${ENV}
  namespace: luck
  labels:
    app: simple-app
    env: ${ENV}
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: simple-app
    env: ${ENV}
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: simple-app-${ENV}
  namespace: luck
spec:
  rules:
  - host: simple-app-${ENV}.workshop.jsleague.ro
    http:
      paths:
      - backend:
          serviceName: simple-app-${ENV}
          servicePort: 80
